; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "ForecastARMA "
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "СоколоваАС"
!define PRODUCT_WEB_SITE "sokolova-nastia96@mail.ru"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\AppMainExe.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME

; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "ForecastARMA "
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\AppMainExe.exe"
!define MUI_FINISHPAGE_SHOWREADME "$INSTDIR\ForecastARMA.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Russian"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "setup.exe"
InstallDir "$PROGRAMFILES\ForecastARMA "
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\ui_widget.h"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\ui_seconddialog.h"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\ui_plot.h"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\ui_inaccuracyhistogram.h"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\ui_editwidget.h"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\ssleay32.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\readme.txt"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5Widgets.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5WebSockets.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5WebKitWidgets.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5WebKit.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5WebChannel.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5Sql.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5Sensors.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5Quick.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5Qml.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5PrintSupport.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5Positioning.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5OpenGL.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5Network.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5MultimediaWidgets.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5Multimedia.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5Gui.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\Qt5Core.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\moc_widget.cpp"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\moc_seconddialog.cpp"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\moc_qcustomplot.cpp"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\moc_predefs.h"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\moc_plotdialog.cpp"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\moc_mymenu.cpp"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\moc_inaccuracyhistogram.cpp"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\moc_editdialog.cpp"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\login.png"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\libxslt-1.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\libxml2-2.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\libwinpthread-1.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\libstdc++-6.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\libssl-1_1.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\libgcc_s_dw2-1.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\lang_ru.qm"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\icuuc57.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\icuin57.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\icudt57.dll"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\ForecastARMA.exe"
  File "..\build-SQLiteDataBase-Desktop_Qt_5_9_0_MinGW_32bit-Release\release\DataBase.db"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\ForecastARMA .lnk" "$INSTDIR\AppMainExe.exe"
  CreateShortCut "$DESKTOP\ForecastARMA .lnk" "$INSTDIR\AppMainExe.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\AppMainExe.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\AppMainExe.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "Удаление программы $(^Name) было успешно завершено."
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Вы уверены в том, что желаете удалить $(^Name) и все компоненты программы?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\DataBase.db"
  Delete "$INSTDIR\ForecastARMA.exe"
  Delete "$INSTDIR\icudt57.dll"
  Delete "$INSTDIR\icuin57.dll"
  Delete "$INSTDIR\icuuc57.dll"
  Delete "$INSTDIR\lang_ru.qm"
  Delete "$INSTDIR\libgcc_s_dw2-1.dll"
  Delete "$INSTDIR\libssl-1_1.dll"
  Delete "$INSTDIR\libstdc++-6.dll"
  Delete "$INSTDIR\libwinpthread-1.dll"
  Delete "$INSTDIR\libxml2-2.dll"
  Delete "$INSTDIR\libxslt-1.dll"
  Delete "$INSTDIR\login.png"
  Delete "$INSTDIR\moc_editdialog.cpp"
  Delete "$INSTDIR\moc_inaccuracyhistogram.cpp"
  Delete "$INSTDIR\moc_mymenu.cpp"
  Delete "$INSTDIR\moc_plotdialog.cpp"
  Delete "$INSTDIR\moc_predefs.h"
  Delete "$INSTDIR\moc_qcustomplot.cpp"
  Delete "$INSTDIR\moc_seconddialog.cpp"
  Delete "$INSTDIR\moc_widget.cpp"
  Delete "$INSTDIR\Qt5Core.dll"
  Delete "$INSTDIR\Qt5Gui.dll"
  Delete "$INSTDIR\Qt5Multimedia.dll"
  Delete "$INSTDIR\Qt5MultimediaWidgets.dll"
  Delete "$INSTDIR\Qt5Network.dll"
  Delete "$INSTDIR\Qt5OpenGL.dll"
  Delete "$INSTDIR\Qt5Positioning.dll"
  Delete "$INSTDIR\Qt5PrintSupport.dll"
  Delete "$INSTDIR\Qt5Qml.dll"
  Delete "$INSTDIR\Qt5Quick.dll"
  Delete "$INSTDIR\Qt5Sensors.dll"
  Delete "$INSTDIR\Qt5Sql.dll"
  Delete "$INSTDIR\Qt5WebChannel.dll"
  Delete "$INSTDIR\Qt5WebKit.dll"
  Delete "$INSTDIR\Qt5WebKitWidgets.dll"
  Delete "$INSTDIR\Qt5WebSockets.dll"
  Delete "$INSTDIR\Qt5Widgets.dll"
  Delete "$INSTDIR\readme.txt"
  Delete "$INSTDIR\SQLiteDataBase.exe"
  Delete "$INSTDIR\ssleay32.dll"
  Delete "$INSTDIR\ui_editwidget.h"
  Delete "$INSTDIR\ui_inaccuracyhistogram.h"
  Delete "$INSTDIR\ui_plot.h"
  Delete "$INSTDIR\ui_seconddialog.h"
  Delete "$INSTDIR\ui_widget.h"
  Delete "$INSTDIR\Example.file"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\Website.lnk"
  Delete "$DESKTOP\ForecastARMA .lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\ForecastARMA .lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR"


  SetAutoClose true
SectionEnd